### PR TITLE
Add note regarding adb sideload

### PR DESCRIPTION
**Pull request by vlad-ivanov-name**

### CODE REVIEW

**Comment by Lanchon** [comment]
hi, thanks

interesting. i did this:

``` bash
echo 'echo "$1"' >name.sh
flashize name.sh
adb sideload name.sh.zip
```

and got this:

```
sideload-host file size 1617 block size 65536
Installing '/sideload/package.zip'...
I:Zip does not contain SELinux file_contexts file in its root.
I:Legacy property environment initialized.

/sideload/package.zip

[OK]

I:Legacy property environment disabled.
I:Signaling child sideload process to exit.
sideload_host finished
```

i saw that TWRP's sideload filename is a constant:
https://github.com/omnirom/android_bootable_recovery/blob/d6821a11bb6d664283ae96030044270ad68eaed0/fuse_sideload.h

i thought of fixing this, but this comes straight from AOSP.

moreover, the sideload-host command is parsed in these two points:
https://github.com/omnirom/android_bootable_recovery/blob/d6821a11bb6d664283ae96030044270ad68eaed0/minadbd/services.c#L136
https://github.com/omnirom/android_bootable_recovery/blob/d6821a11bb6d664283ae96030044270ad68eaed0/minadbd/services.c#L50

and the command is formatted here:
https://gitlab.com/pbeeler/system_core/blob/71fe584a1a7256c057267ae46a35f7c74d1d549e/adb/commandline.c#L541

it looks like the filename is not passed on from the adb client at all, which means that there is no fixing this.

i'll think about what to do... thanks!

**Comment by Lanchon** [comment]
i should implement #4.
but for now... bffc12e1e564af5d749aee9cffd4590ef7db774e
thank you!

**Comment by vlad-ivanov-name** [comment]
thank you too for the awesome tool!

**Comment by Lanchon** [comment]
now sideloading is supported.

**Pull request closed without merging**
